inherit_from:
  - .rubocop_performance.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/bundle/**/*"
    - "db/**/*"
    - "spec/factories/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "app/views/**/*"
    - "config/deploy.rb"
    - "config/initializers/**/*"
    - "Rakefile"
    - "spec/support/**/*"
    - "spec/**/*"
    - "config/**/*"
    - "Gemfile"

Layout/LineLength:
  AllowedPatterns: ['\A\s*#']
  Max: 110

Layout/BlockAlignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
